### ISSUE TITLE
migrate get error

### ISSUE THREAD

**Issue by coffemate** [yhuag/The-Neon-Network-ECoupons-On-Blockchain#1]
```
Using network 'development'.

Running migration: 1_initial_migration.js
  Replacing Migrations...
  ... 0xbf1cb62c5d6c2178433bf394152086791b320ab0acb3177c4a7e09e96816d4a8
  Migrations: 0x37543ec47951e1c912b76aef151a02d847a0b287
Saving successful migration to network...
  ... 0x8d32424bb4a6d814a6507d63fbfd88c0746919b3bf3cd350bf4387603dc9066d
Saving artifacts...
Running migration: 2_deploy_contracts.js
  Deploying Coupon...
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: Coupon contract constructor expected 5 arguments, received 0
    at /home/coffee/installfile/node-v6.10.0-linux-x64/lib/node_modules/truffle/build/webpack:/~/truffle-contract/contract.js:388:1
    at /home/coffee/installfile/node-v6.10.0-linux-x64/lib/node_modules/truffle/build/webpack:/~/truffle-contract/contract.js:372:1
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

use ganache cli 6.0.3

**Comment by nithinkumarhere** [comment]
downgrade your truffle to 4.0.0. It works for me.
